services:
  gitlab:
    image: gitlab/gitlab-ce:nightly
    container_name: gitlab
    restart: always
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    expose:
      - 80
      - 443
    networks:
      - gitlab
    volumes:
      - ./gitlab-config:/etc/gitlab
      - ./gitlab-logs:/var/log/gitlab
      - ./gitlab-data:/var/opt/gitlab
  db:
    image: postgres:17.4-alpine
    container_name: db
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=NFL
      - POSTGRES_DB=NFLIT
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "NFL", "-d", "NFLIT"]
      interval: 5s
      timeout: 10s
      retries: 20
  web:
    environment:
      - DATABASE_URL=postgresql://NFL:root@db:5432/NFLIT
      - NODE_ENV=production
      - JWT_SECRET_KEY=secret
    build: .
    container_name: web
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  database:
    driver: local

networks:
  default:
    driver: bridge