services:
  gitlab:
    image: gitlab/gitlab-ce:nightly
    restart: always
    container_name: gitlab
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        external_url 'http://localhost'
  db:
    image: postgres:17.4-alpine
    container_name: db
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=NFL
      - POSTGRES_DB=NFLIT
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "NFL", "-d", "NFLIT"]
      interval: 5s
      timeout: 10s
      retries: 20
  web:
    environment:
      - DATABASE_URL=postgresql://NFL:root@db:5432/NFLIT
      - NODE_ENV=production
      - JWT_SECRET_KEY=secret
    build: .
    container_name: web
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  database:
    driver: local

  gitlab-config:
    driver: local

  gitlab-logs:
    driver: local

  gitlab-data:
    driver: local

networks:
  default:
    driver: bridge